# Permalinks
permalink:           pretty

# Setup
title:               Gil Serra
tagline:             About iOS development
url:                 "https://gilserrap.github.io/blog"
paginate:            1
baseurl:             "https://gilserrap.github.io/blog"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed


# About/contact
author:
  name:              Gil Serra
  url:               https://twitter.com/gilserrap
  email:             gilserrap@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/gilserrap/blog

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
